<?php

return [
    [
            'id' => 'ukhmt',
            'name' => 'UK. HM Treasury',
            'url' => 'http://hmt-sanctions.s3.amazonaws.com/sanctionsconlist.csv',
            'more info' => 'https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets/consolidated-list-of-targets',
            'format guide' => 'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/292095/fin_sanc_consolidated_list_format_guide.pdf',
            'updates' => '',
            'folder' => 'ukhmt',
            'filename' => 'ukhmt',
            'format' => 'csv',
            'class' => 'Ukhmt',
    ],
    [
            'id' => 'usofac',
            'name' => 'US. Department of the Treasury. SDN List',
            'url' => 'http://www.treasury.gov/ofac/downloads/sdn.xml',
            'more info' => 'https://www.treasury.gov/resource-center/sanctions/SDN-List/Pages/consolidated.aspx',
            'format guide' => '',
            'updates' => '',
            'folder' => 'usofac',
            'filename' => 'usofac',
            'format' => 'xml',
            'class' => 'Usofac',
    ],
    [
            'id' => 'unsc',
            'name' => 'Un. Consolidated United Nations Security Council Sanctions List',
            'url' => 'https://www.un.org/sc/suborg/sites/www.un.org.sc.suborg/files/consolidated.xml',
            'more info' => 'https://www.un.org/sc/suborg/en/sanctions/un-sc-consolidated-list',
            'format guide' => 'Info: https://www.un.org/sc/suborg/en/sanctions/un-sc-consolidated-list#composition%20list; XSD: https://www.un.org/sc/resources/sc-sanctions.xsd',
            'updates' => '',
            'folder' => 'unsc',
            'filename' => 'unsc',
            'format' => 'xml',
            'class' => 'Unsc',
    ],
];
