language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - mkdir lists
    - mkdir output
    - echo "memory_limit=256M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - php src/OpenList/Receiver.php
    - php src/OpenList/Processor.php
    - phpunit --verbose --coverage-clover build/logs/clover.xml
    - phpenv config-rm xdebug.ini || return 0
    - php php-cs-fixer --diff --dry-run -v fix

after_success:
    - php vendor/bin/coveralls -v
